name: ⚙️ Test S3 Deploy

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-s3-deploy:
    uses: aligent/actions/.github/workflows/static-hosting-deployment.yml@feat/s3-deploy
